apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: projectscreator/mmsrv-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: projectscreator/mmsrv-comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.ts"
            dest: .
    - image: projectscreator/mmsrv-event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.ts"
            dest: .
    - image: projectscreator/mmsrv-moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.ts"
            dest: .
    - image: projectscreator/mmsrv-posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.ts"
            dest: .
    - image: projectscreator/mmsrv-query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.ts"
            dest: .
    - image: projectscreator/mmsrv-tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.ts"
            dest: .
